spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beverages-partners
    username: zezinho
    password: any-strong-secured-password

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect