spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beverages_partners
    username: zezinho
    password: any-strong-secured-password

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect